name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}

          server-dir: /

          exclude: |
            **/.git*
            **/node_modules/**
            **/vendor/**
            **/.env*
            **/.github/**
            **/tests/**
            **/phpunit.xml
            **/.phpunit.cache/**
            **/.idea/**
            **/.vscode/**
            **/.fleet/**
            **/docker/**
